version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME:-backend_colab_db}
    environment:
      POSTGRES_DB: ${DB_NAME:-backend_colab_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5433}:5432"
    restart: unless-stopped

volumes:
  postgres_data: